name: Build NHL Setup Binaries

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build_32bit:
    runs-on: ubuntu-22.04
    name: Build 32-bit binary
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build on 32-bit ARM
        uses: pguyot/arm-runner-action@v2
        with:
          base_image: raspios_lite:latest
          commands: |
            apt-get update
            apt-get install -y python3-full python3-venv python3-pip
            cd /tmp
            python3 -m venv .venv
            /tmp/.venv/bin/pip install -r requirements.txt
            SITE_PACKAGES=$(/tmp/.venv/bin/python -c "import site; print(site.getsitepackages()[0])")
            /tmp/.venv/bin/pyinstaller --onefile --add-data "$SITE_PACKAGES/pyfiglet:./pyfiglet" nhl_setup.py -n nhl_setup.32
            ls -la /tmp
          arch: arm7l
          cpu: cortex-a7
          cpu_info: cpuinfo/raspberrypi_3b

      - name: Upload 32-bit artifact
        uses: actions/upload-artifact@v4
        with:
          name: nhl_setup.32
          path: dist/nhl_setup.32

  build_64bit:
    runs-on: ubuntu-22.04
    name: Build 64-bit binary
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build on 64-bit ARM
        uses: pguyot/arm-runner-action@v2
        with:
          base_image: raspios_lite_arm64:latest
          commands: |
            apt-get update
            apt-get install -y python3-full python3-venv python3-pip
            cd /tmp
            python3 -m venv .venv
            /tmp/.venv/bin/pip install -r requirements.txt
            SITE_PACKAGES=$(/tmp/.venv/bin/python -c "import site; print(site.getsitepackages()[0])")
            /tmp/.venv/bin/pyinstaller --onefile --add-data "$SITE_PACKAGES/pyfiglet:./pyfiglet" nhl_setup.py -n nhl_setup.64
            ls -la /tmp
          arch: aarch64
          cpu: cortex-a53
          cpu_info: cpuinfo/raspberrypi_zero2_w_arm64

      - name: Upload 64-bit artifact
        uses: actions/upload-artifact@v4
        with:
          name: nhl_setup.64
          path: dist/nhl_setup.64

  release:
    needs: [build_32bit, build_64bit]
    runs-on: ubuntu-latest
    name: Upload to release
    permissions:
      contents: write
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist
          merge-multiple: true

      - name: Upload to latest release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/nhl_setup.32
            dist/nhl_setup.64
